Laboratorios/Models/Authentication/NuevaContrasena.cs
using System.ComponentModel.DataAnnotations;

namespace Isp.Laboratorios.Models.Authentication
{
    public class NuevaContrasena
    {
        [Required(ErrorMessage = "El enlace es incorrecto")]
        public string DataEnlace { get; set; }

        [Required(ErrorMessage = "Ingrese Correo")]
        [Compare("DataEnlace", ErrorMessage = "Correo incorrecto para recuperación de contraseña")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Ingrese nueva contraseña")]
        [StringLength(40, ErrorMessage = "la Contraseña tiene que tener al menos {2} caracteres de largo.", MinimumLength = 6)]
        public string ContrasenaNueva { get; set; }

        [Required(ErrorMessage = "Reingrese nueva contraseña")]
        [Compare("ContrasenaNueva", ErrorMessage = "Las contraseñas deben ser iguales")]
        public string ContrasenaNuevaAConfirmar { get; set; }

    }
}

Laboratorios/Controllers/CuentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using Isp.Laboratorios.DataAccessLayer;
using Isp.Laboratorios.Infrastructure;
using Isp.Laboratorios.Infrastructure.Security.Authorization;
using Isp.Laboratorios.Infrastructure.Security.Encrypting;
using Isp.Laboratorios.Models;
using Isp.Laboratorios.Models.Authentication;
using Membership = Isp.Laboratorios.Infrastructure.Security.Authentication.Membership;

namespace Isp.Laboratorios.Controllers
{
    public class CuentasController : Controller
    {
        readonly UnitOfWork _db = new UnitOfWork();

        public ActionResult IniciarSesion(Login login)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidarUsuario(login))
                {
                    FormsAuthentication.SetAuthCookie(login.UserName, false);

                    return RedirectToAction("Index", "Home");

                }
                Alert.Information(this, "Nombre de usuario o contraseña no válidos");
            }
            login.UserName = string.Empty;
            login.Password = string.Empty;
            return View(login);
        }
        [RequiresAuthorization]
        public ActionResult CerrarSesion()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("IniciarSesion");
        }
        public ActionResult DesplegarMenu()
        {
            List<Funcionalidad> funcionalidades = Membership.ObtenerFuncionalidades(ApplicationInfo.CurrentUser.Id);
            ViewBag.NombreCompleto = Membership.ObtenerNombreUsuarioCompleto();

            return View(funcionalidades);
        }
        [RequiresAuthorization]
        public ActionResult CambiarContrasenaFea()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CambiarContrasenaFea(CambioContrasena cambioContrasena)
        {
            if (ModelState.IsValid)
            {
                var usuario = ApplicationInfo.CurrentUser;

                if (usuario.ContrasenaFEA.Equals(Sha1.Encrypt(cambioContrasena.ContrasenaActual)))
                {
                    usuario.ContrasenaFEA = Sha1.Encrypt(cambioContrasena.ContrasenaNueva);
                    _db.Usuarios.Actualizar(usuario);
                    _db.GuardarCambios();
                    Alert.Success(this, "La contraseña de Firma Electrónica se actualizó correctamente");
                    return View(new CambioContrasena());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "La contraseña actual ingresada no coincide con su contraseña de Firma Electrónica");
                }
            }
            Alert.Danger(this, Alert.GetAllErrorModel(ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors)));
            return View(new CambioContrasena());

        }
        [RequiresAuthorization]
        public ActionResult CambiarContrasena()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CambiarContrasena(CambioContrasena cambioContrasena)
        {
            if (ModelState.IsValid)
            {
                var usuario = ApplicationInfo.CurrentUser;

                if (usuario.Contrasena.Equals(Sha1.Encrypt(cambioContrasena.ContrasenaActual)))
                {
                    usuario.Contrasena = Sha1.Encrypt(cambioContrasena.ContrasenaNueva);
                    _db.Usuarios.Actualizar(usuario);
                    _db.GuardarCambios();
                    Alert.Success(this, "La contraseña se actualizó correctamente");
                    return View(new CambioContrasena());
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "La contraseña actual ingresada no coincide con su contraseña");
                }
            }
            Alert.Danger(this, Alert.GetAllErrorModel(ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors)));
            return View(new CambioContrasena());

        }
        public ActionResult RecuperarContrasena()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RecuperarContrasena(string correo)
        {
            var usuario = _db.Usuarios.ObtenerPorCorreo(correo);

            if (usuario != null)
            {
                string ruta = ApplicationInfo.PlantillaCambioContrasena;
                System.IO.File.ReadAllText(ruta, Encoding.UTF8);
                string htmlString = System.IO.File.ReadAllText(ruta, Encoding.UTF8);
                var fechaValidez = DateTime.Now.ToShortDateString();
                var bytes = Encoding.UTF8.GetBytes(fechaValidez + usuario.CorreoElectronico);
                var base64 = Convert.ToBase64String(bytes);

                var tokens = new Dictionary<string, string>
                                                {
                                                    {"[SistemaNombre]",ApplicationInfo.NombreSistema},
                                                    {"[Usuario]", usuario.Nombre},
                                                    {"[FechaValidez]",fechaValidez},
                                                    {"[UrlCambioContrasena]",ApplicationInfo.UrlCambioContrasena +base64}
                                                };

                var mensaje = Util.ReplaceTokens(htmlString, tokens);
                string asunto = "Recuperar Contraseña Sistema: " + ApplicationInfo.NombreSistema;
                var mail = Mail.Generar(ApplicationInfo.MailSistema, asunto, usuario.CorreoElectronico, mensaje);

                if (Mail.Enviar(mail))
                {
                    Alert.Success(this, "Se ha enviado un correo electrónico con instrucciones para recuperar su contraseña", false);
                    return RedirectToAction("IniciarSesion");
                }

                Alert.Danger(this, "Ha ocurrido un error al enviar correo electrónico");
                return View();

            }
            Alert.Information(this, "El correo ingresado no se encuentra registrado");
            return View();
        }

        public ActionResult NuevaContrasena(string recover)
        {
            var nuevaContrasena = new NuevaContrasena();
            try
            {
                var bytes = Convert.FromBase64String(recover);
                var cadena = Encoding.UTF8.GetString(bytes);

                var fecha = cadena.Substring(0, 10);

                if (fecha == DateTime.Now.ToShortDateString())
                {
                    nuevaContrasena.DataEnlace = cadena.Substring(10);
                }
                else
                {
                    Alert.Information(this, "El enlace de recuperación caducó, debe realizar otra solicitud de recuperación de contraseña", false);
                    return RedirectToAction("IniciarSesion");
                }
            }
            catch (Exception)
            {
                Alert.Danger(this, "El enlace está dañado o no es válido", false);
                return RedirectToAction("IniciarSesion");
            }


            return View(nuevaContrasena);
        }

        [HttpPost]
        public ActionResult NuevaContrasena(NuevaContrasena nuevaContrasena)
        {
            if (ModelState.IsValid)
            {
                var usuario = _db.Usuarios.ObtenerPorCorreo(nuevaContrasena.Correo);
                usuario.Contrasena = Sha1.Encrypt(nuevaContrasena.ContrasenaNueva);
                _db.Usuarios.Actualizar(usuario);
                Alert.Success(this, "La contraseña se actualizó correctamente");
                return RedirectToAction("IniciarSesion");
            }

            Alert.Danger(this, Alert.GetAllErrorModel(ViewData.ModelState.Values.SelectMany(modelState => modelState.Errors)));
            return View(nuevaContrasena);
        }
    }
}

Laboratorios/Views/Cuentas/CambiarContrasena.cshtml
@model Isp.Laboratorios.Models.Authentication.CambioContrasena
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Cambiar Contraseña";
}

@using (Html.BeginForm("CambiarContrasena", "Cuentas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
{
    <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="jumbotron">
                @Html.AntiForgeryToken()
                <h3> @ViewBag.Title </h3>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.ContrasenaActual, null, new { @class = "form-control", placeholder = "Contraseña Actual", type = "password", required = "required" })<br />
                    @Html.TextBoxFor(m => m.ContrasenaNueva, null, new { @class = "form-control", placeholder = "Nueva Contraseña", type = "password", required = "required" })<br />
                    @Html.TextBoxFor(m => m.ContrasenaNuevaAConfirmar, null, new { @class = "form-control", placeholder = "Repita nueva contraseña", type = "password", required = "required" })<br />
                    <input type="submit" value="Realizar Cambio" class="btn btn-lg btn-primary btn-block" id="btnSubmit" />
                </div>
            </div>
        </div>
    </div>
}

Laboratorios/Views/Cuentas/CambiarContrasenaFea.cshtml
@model Isp.Laboratorios.Models.Authentication.CambioContrasena
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Cambiar Contraseña Firma Electrónica Avanzada";
}

@using (Html.BeginForm("CambiarContrasenaFea", "Cuentas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
{
    <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="jumbotron">
                @Html.AntiForgeryToken()
                <h3>Cambiar Contraseña FEA</h3>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.ContrasenaActual, null, new { @class = "form-control", placeholder = "Contraseña Actual", type = "password", required = "required" })<br />
                    @Html.TextBoxFor(m => m.ContrasenaNueva, null, new { @class = "form-control", placeholder = "Nueva Contraseña", type = "password", required = "required" })<br />
                    @Html.TextBoxFor(m => m.ContrasenaNuevaAConfirmar, null, new { @class = "form-control", placeholder = "Repita nueva contraseña", type = "password", required = "required" })<br />
                    <input type="submit" value="Realizar Cambio" class="btn btn-lg btn-primary btn-block" id="btnSubmit" />
                </div>
            </div>
        </div>
    </div>
}

Laboratorios/Views/Cuentas/DesplegarMenu.cshtml
@model IEnumerable<Isp.Laboratorios.Models.Funcionalidad>
@{
    Layout = null;
}
<ul class="nav navbar-nav">
    @foreach (var funcionalidad in Model.Where(f => f.ALaDerecha != true))
    {
        <li class="dropdown">
            @(funcionalidad.Funcionalidades.Any() 
            ? Html.Raw(String.Format("<a class='dropdown-toggle' data-toggle='dropdown' href='/{0}/{1}'>{2} <span class='caret'></span></a>", funcionalidad.Controlador, funcionalidad.Accion, funcionalidad.Titulo)) 
            : Html.Raw(String.Format("<a href='/{0}/{1}'>{2}</a>", funcionalidad.Controlador, funcionalidad.Accion, funcionalidad.Titulo)))

            <ul class="dropdown-menu" role="menu">
                @foreach (var funcionalidadHija in funcionalidad.Funcionalidades)
                {
                    <li>
                        @Html.ActionLink(funcionalidadHija.Titulo, funcionalidadHija.Accion, funcionalidadHija.Controlador)
                    </li>
                }
            </ul>
        </li>
    }
</ul>
<ul class="nav navbar-nav navbar-right">
    @foreach (var funcionalidad in Model.Where(f => f.ALaDerecha))
    {
        <li class="dropdown">
            @Html.Raw(String.Format("<a class='dropdown-toggle' data-toggle='dropdown' href='/{0}/{1}'>{2} <span class='badge alert-danger'>0</span><span class='caret'></span></a>", funcionalidad.Controlador, funcionalidad.Accion, funcionalidad.Titulo.Replace("[NOMBRE_USUARIO]", @ViewBag.NombreCompleto), @ViewBag.Rol))
            <ul class="dropdown-menu" role="menu">
                @foreach (var funcionalidadHija in funcionalidad.Funcionalidades)
                {
                    <li>
                        @Html.ActionLink(funcionalidadHija.Titulo, funcionalidadHija.Accion, funcionalidadHija.Controlador, null, new { @class = "text-right" })
                    </li>
                }

            </ul>
        </li>
    }
</ul>

Laboratorios/Views/Cuentas/IniciarSesion.cshtml
@using Isp.Laboratorios.Infrastructure
@model Isp.Laboratorios.Models.Authentication.Login
@{
    Layout = "~/Views/Shared/_LayoutOffline.cshtml";
    ViewBag.Title = "Iniciar sesión - " + ApplicationInfo.NombreSistema;
}

@using (Html.BeginForm("IniciarSesion", "Cuentas", FormMethod.Post, new { @class = "form-signin", role = "form" }))
{
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <div class="col-md-offset-3 col-md-6 col-md-offset-3">
            <div class="jumbotron">
                <h3>Inicie Sesión</h3>
                @Html.AntiForgeryToken()
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder = "Usuario", required = "required" })<br />
                @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Contraseña", required = "required" })<br />
                <div class="form-group">
                    @Html.ActionLink("Recuperar Contraseña", "RecuperarContrasena", "Cuentas")
                </div>
                <div class="form-group">
                    <input type="submit" value="Iniciar sesión" class="btn btn-lg btn-primary btn-block" id="btnSubmit" />
                </div>
            </div>
        </div>
    </div>

}

Laboratorios/Views/Cuentas/NuevaContrasena.cshtml
@model Isp.Laboratorios.Models.Authentication.NuevaContrasena
@{
    Layout = "~/Views/Shared/_LayoutOffline.cshtml";
    ViewBag.Title = "Nueva Contraseña";
}


@using (Html.BeginForm("NuevaContrasena", "Cuentas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-signin", role = "form" }))
{
    <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="jumbotron">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.DataEnlace)
                <h3>class="form-signin"> @ViewBag.Title </h3>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.Correo, null, new { @class = "form-control", placeholder = "Correo electrónico", type = "email", required = "required" })<br />
                    @Html.TextBoxFor(m => m.ContrasenaNueva, null, new { @class = "form-control", placeholder = "Nueva Contraseña", type = "password", required = "required" })<br />
                    @Html.TextBoxFor(m => m.ContrasenaNuevaAConfirmar, null, new { @class = "form-control", placeholder = "Repita nueva contraseña", type = "password", required = "required" })<br />
                    <input type="submit" value="Crear Nueva contraseña" class="btn btn-lg btn-primary btn-block" id="btnSubmit" />
                </div>
                }
            </div>
        </div>
    </div>
}

Laboratorios/Views/Cuentas/RecuperarContrasena.cshtml
@{
    Layout = "~/Views/Shared/_LayoutOffline.cshtml";
    ViewBag.Title = "Recuperar Contraseña";
}

@using (Html.BeginForm("RecuperarContrasena", "Cuentas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-signin", role = "form" }))
{    <div class="col-md-offset-3 col-md-6 col-md-offset-3">
        <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="jumbotron">
                @Html.AntiForgeryToken()
                <h3>Recuperar Contraseña</h3>
                <div class="form-group">
                    @Html.TextBox("correo", null, new { @class = "form-control", placeholder = "Correo electrónico", required = "required", type = "email" })<br />
                    <input type="submit" value="Recuperar Contraseña" class="btn btn-lg btn-primary btn-block" />
                </div>
            </div>
        </div>
    </div>
}