Laboratorios/Models/ViewModels/IngresoResultadoViewModel.cs
using System.Collections.Generic;

namespace Isp.Laboratorios.Models.ViewModels
{
    public class IngresoResultadoViewModel
    {
        public IngresoResultadoViewModel()
        {
            ResultadosAnalitos = new List<ResultadoAnalitoViewModel>();
            MuestraIdList = new List<int>();
            AnalitoIdList = new List<int>();
            ExamenIdList = new List<int>();
        }
        public List<int> MuestraIdList { get; set; }
        public List<int> ExamenIdList { get; set; }
        public List<int> AnalitoIdList { get; set; }
        public int PrestacionId { get; set; }
        public int MetodoId { get; set; }
        public int NormaId { get; set; }
        public int LimiteCuantificacionId { get; set; }
        public int LimiteDeteccionId { get; set; }
        public int LimiteMaximoPermitidoId { get; set; }
        public int UnidadMedidaId { get; set; }
        public string Resultado { get; set; }
        public string Observacion { get; set; }
        public List<ResultadoAnalitoViewModel> ResultadosAnalitos { get; set; }
    }
}

Laboratorios/Controllers/ResultadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using Isp.Laboratorios.DataAccessLayer;
using Isp.Laboratorios.Infrastructure;
using Isp.Laboratorios.Models;
using Isp.Laboratorios.Models.Enums;
using Isp.Laboratorios.Models.ViewModels;
using Microsoft.Security.Application;

namespace Isp.Laboratorios.Controllers
{
    public class ResultadosController : Controller
    {
        private readonly UnitOfWork _db = new UnitOfWork();
        private readonly Usuario _usuario = ApplicationInfo.CurrentUser;

        public ActionResult ParaIngresoResultados()
        {
            var filtroBusqueda = new FiltroBusqueda
            {
                Laboratorios = new SelectList(_db.Laboratorios.ObtenerPorUsuarioId(_usuario.Id), "Id", "Nombre"),
                ExamenEstado = (int)EstadoExamen.IngresoResultados
            };
            ViewBag.FiltroBusqueda = filtroBusqueda;

            var muestras = _db.Muestras.Obtener(filtroBusqueda);

            var model = Mapper.Map<IEnumerable<Muestra>, IEnumerable<MuestraViewModel>>(muestras);
            return View(model);
        }

        public ActionResult IngresoResultados(List<int> examenesId)
        {
            var examenes = _db.Examenes.ObtenerPorIds(examenesId);
            var muestras = examenes.Select(x => x.Muestra).ToList();

            ViewBag.lblMuestraCodigo = string.Join(", ", muestras.Select(x => x.Codigo).Distinct());

            ViewBag.TipoMuestraNombre = string.Join(", ", muestras.Select(x => x.TipoMuestra.Nombre).Distinct());

            var prestaciones = examenes.Select(x => x.Prestacion).ToList();
            ViewBag.ddlPrestaciones = new SelectList(prestaciones, "Id", "Nombre");

            var analitos = _db.Analitos.ObtenerPorPrestaciones(prestaciones);

            ViewBag.MuestraIdList = muestras.Select(x => x.Id).ToList();
            ViewBag.ExamenIdList = examenesId;
            ViewBag.AnalitoIdList = analitos.Select(x => x.Id).ToList();

            ViewBag.ddlMetodos = new SelectList(_db.Metodos.ObtenerPorAnalitos(analitos), "Id", "Nombre");

            ViewBag.ddlNormas = new SelectList(_db.Normas.ObtenerTodo(), "Id", "Nombre");

            ViewBag.ddlLimitesCuantificaciones = new SelectList(_db.LimitesCuentificaciones.ObtenerTodo(), "Id", "Nombre");

            ViewBag.ddlLimitesDetecciones = new SelectList(_db.LimitesDetecciones.ObtenerTodo(), "Id", "Nombre");

            ViewBag.ddlLimitesMaximosPermitidos = new SelectList(_db.LimitesMaximosPermitidos.ObtenerTodo(), "Id", "Nombre");

            ViewBag.ddlUnidadesMedida = new SelectList(_db.UnidadesMedidas.ObtenerTodo(), "Id", "Nombre");


            var ra = _db.ResultadosAnalitos.ObtenerPorExamenIds(ViewBag.ExamenIdList as List<int>);
            var model = new IngresoResultadoViewModel
            {
                ResultadosAnalitos =  Mapper.Map<List<ResultadoAnalito>, List<ResultadoAnalitoViewModel>>(ra)
            };
            if (Request.IsAjaxRequest())
            {
                return PartialView("IngresoResultadosMasivo",model);
            }
            return View(model);
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult RechazarARecepcionLaboratorio(string muestrasIdChecked, string rechazoComentario, int motivoRechazo, bool enviarMail = false)
        {
            var muestrasId = muestrasIdChecked.Split(',').Select(Int32.Parse).ToList();

            var filtroBusqueda = new FiltroBusqueda
            {
                Laboratorios = new SelectList(_db.Laboratorios.ObtenerPorUsuarioId(_usuario.Id), "Id", "Nombre"),
                ExamenEstado = (int)EstadoExamen.IngresoResultados
            };
            ViewBag.FiltroBusqueda = filtroBusqueda;

            var examenes = _db.Examenes.ObtenerPorMuestraLaboratorio(muestrasId, filtroBusqueda.LaboratoriosId);
            rechazoComentario = Sanitizer.GetSafeHtmlFragment(rechazoComentario);//antiXss
            var fechaRechazo = DateTime.Now;
            foreach (var examen in examenes)
            {

                examen.EstadoId = (int)EstadoExamen.RecepcionLaboratorio;
                examen.Observacion = rechazoComentario;

                var rechazo = new Rechazo
                {
                    UsuarioId = _usuario.Id,
                    ExamenId = examen.Id,
                    Fecha = fechaRechazo,
                    MotivoRechazoId = motivoRechazo,
                    Observacion = rechazoComentario
                };

                _db.Rechazos.Insertar(rechazo);
            }
            _db.BitacoraExamenes.Insertar(examenes, _usuario.Id);

            if (enviarMail)
            {
                //envio de mail por muestra
                foreach (var muestraId in muestrasId)
                {
                    var muestra = _db.Muestras.ObtenerPorId(muestraId);
                    var laboratorio = _db.Laboratorios.ObtenerPorMuestraId(muestraId);
                    var responsableRtm = _db.Usuarios.ObtenerResponsableRtm();

                    string ruta = ApplicationInfo.PlantillaRechazo;
                    System.IO.File.ReadAllText(ruta, Encoding.UTF8);
                    string htmlString = System.IO.File.ReadAllText(ruta, Encoding.UTF8);

                    var tokens = new Dictionary<string, string>
                                                {
                                                    {"[SistemaNombre]",ApplicationInfo.NombreSistema},
                                                    {"[UsuarioOrigen]",_usuario.Nombre + " " +_usuario.ApellidoPaterno},
                                                    {"[UsuarioDestino]",responsableRtm.Nombre + " "+responsableRtm.ApellidoPaterno},
                                                    {"[MuestraCodigo]",muestra.Codigo},
                                                    {"[LaboratorioNombre]",laboratorio.Nombre},
                                                    {"[ProcedenciaNombre]",muestra.Solicitud.Procedencia.Nombre},
                                                    {"[Comentario]",rechazoComentario}
                       
                                                };

                    var mensaje = Util.ReplaceTokens(htmlString, tokens);

                    string asunto = "Notificación de Rechazos de la Muestra :" + muestra.Codigo + " " + ApplicationInfo.NombreSistema;

                    var mail = Mail.Generar(ApplicationInfo.MailSistema, asunto, responsableRtm.CorreoElectronico, mensaje, laboratorio.Seccion.ResponsableMail, MailPriority.High);

                    Mail.Enviar(mail);
                }
            }

            _db.GuardarCambios();

            var muestras = _db.Muestras.Obtener(filtroBusqueda);

            var model = Mapper.Map<IEnumerable<Muestra>, IEnumerable<MuestraViewModel>>(muestras);

            Alert.Success(this, string.Format("Se han <b>Rechazado {0} Muestra(s)</b> a Laboratorio", muestrasId.Count));
            return View("ParaIngresoResultados", model);
        }

    }
}

Laboratorios/Views/Resultados/IngresoResultados.cshtml
@using Isp.Laboratorios.Models.ViewModels
@model IngresoResultadoViewModel
@{

    @section Scripts {
        @Scripts.Render("~/bundles/js-chosen")
        @Styles.Render("~/bundles/css-chosen")
        @Scripts.Render("~/bundles/js-grid")
        @Scripts.Render("~/bundles/js-blockUI")}

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Ingreso de Resultados";

}
@using (Html.BeginForm("IngresoResultados", "Resultados", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-info">
        <div class="panel-heading"><b>Ingresando Resultados Muestra</b>: @Html.DisplayText("lblMuestraCodigo")</div>
        <div class="panel-body form-inline">
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Tipo Muestra")
                </div>
                <div class="col-md-10">
                    @Html.DisplayText("TipoMuestraNombre")
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Prestación")
                </div>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.PrestacionId, (SelectList)ViewBag.ddlPrestaciones, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Método")
                </div>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.MetodoId, (SelectList)ViewBag.ddlMetodos, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Norma")
                </div>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.NormaId, (SelectList)ViewBag.ddlNormas, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Límite Cuantificación")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.LimiteCuantificacionId, (SelectList)ViewBag.ddlLimitesCuantificaciones, new { @class = "chosen-select input-sm" })
                </div>
                <div class="col-md-2">
                    @Html.Label("Límite Detección")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.LimiteDeteccionId, (SelectList)ViewBag.ddlLimitesDetecciones, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("LMP")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.LimiteMaximoPermitidoId, (SelectList)ViewBag.ddlLimitesMaximosPermitidos, new { @class = "chosen-select input-sm" })
                </div>
                <div class="col-md-2">
                    @Html.Label("Unidad de Medida")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.UnidadMedidaId, (SelectList)ViewBag.ddlUnidadesMedida, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Analitos")
                </div>
                <div id="chkAnalitos" class="col-md-10">
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Resultado")
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Resultado, string.Empty, new { maxlength = 250, @class = "form-control", required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Observación")
                </div>
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Observacion, new { maxlength = 250, @class = "form-control", @title = "Observación", required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-offset-2 col-md-2">
                    <button type="button" class="btn btn-sm btn-default btn-block" id="btnAgregarAnalito"><span class="glyphicon glyphicon-plus"></span> Agregar Analito</button>
                </div>
            </div>
        </div>
    </div>
    <div id="gridContainer">
        @Html.Partial("_GridIngresoResultados", Model.ResultadosAnalitos)
    </div>
    <div class="row">
        <div class="col-md-offset-5 col-md-3">
            <button type="submit" class="btn btn-primary btn-block" id="btnConfirmarResultado"><span class="glyphicon glyphicon-floppy-disk"></span> Confirmar Resultados</button>
        </div>
    </div>
    <br />
}
<div id="modalRechazoContainer">
    @Html.Partial("_ConfirmarRechazoModal")
</div>
<script type="text/javascript">
    $(document).ready(function () {

        gridFunctionCheckAll();

        $('#PrestacionId, #MetodoId').change(function () {

            $.ajax({
                url: "@Url.Action("ObtenerPorMetodoPrestacion", "Analitos")",
                method: "GET",
                data: {
                    prestacionId: $("#PrestacionId").val(),
                    metodoId: $("#MetodoId").val()
                },
                success: function (result) {

                    var contenido = '';
                    $.each(result, function (index, value) {
                        contenido += '<div class="col-md-3"><label>';
                        contenido += '<input type="checkbox" value=' + value.Id + ' id="checkboxId">';
                        contenido += ' ' + value.Nombre + '</label></div>';
                    });
                    $("#chkAnalitos").html(contenido);
                }
            });
        });
        $('#btnAgregarAnalito').click(function () {
            var analitosIds = [];

            $('input#checkboxId:checked').each(function () {
                analitosIds.push($(this).val());
            });
            
            $.ajax({
                url: "@Url.Action("AgregarResultadoAnalito", "Analitos")",
                method: "POST",

                data: {
                    muestraIdList: JSON.parse('@Html.Raw(Json.Encode(ViewBag.MuestraIdList))'),
                    examenIdList: JSON.parse('@Html.Raw(Json.Encode(ViewBag.ExamenIdList))'),
                    analitoIdList: analitosIds,
                    prestacionId: $("#PrestacionId").val(),
                    metodoId: $("#MetodoId").val(),
                    normaId: $("#NormaId").val(),
                    limiteCuantificacionId: $("#LimiteCuantificacionId").val(),
                    limiteDeteccionId: $("#LimiteDeteccionId").val(),
                    limiteMaximoPermitidoId: $("#LimiteMaximoPermitidoId").val(),
                    unidadMedidaId: $("#UnidadMedidaId").val(),
                    resultado: $("#Resultado").val(),
                    observacion: $("#Observacion").val(),
                    resultadosAnalitos: $("#resultadosAnalitos").val()
                },

                success: function (result) {
                    $("#gridContainer").html(result);
                    renderAlert();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText + " Ha ocurrido un error.");
                }
            });
        });
        $('#gridCheckAll a').click(function (e) {

            console2.log('jojo');

            console.log('jojo' + e.val());
            $.ajax({
                url: $(this).data('urlaction'),
                method: "POST",

                data: {},
                success: function (result) {
                    $("#gridContainer").html(result);
                    renderAlert();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText + " Ha ocurrido un error.");
                }
            });

        });

        $('#PrestacionId').trigger("change");
    });


</script>

Laboratorios/Views/Resultados/IngresoResultadosMasivo.cshtml
@using Isp.Laboratorios.Models.ViewModels
@model IngresoResultadoViewModel
@{

    @section Scripts {
        @Scripts.Render("~/bundles/js-chosen")
        @Styles.Render("~/bundles/css-chosen")
        @Scripts.Render("~/bundles/js-grid")
        @Scripts.Render("~/bundles/js-blockUI")}

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Ingreso de Resultados";

}
@using (Html.BeginForm("IngresoResultados", "Resultados", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-info">
        <div class="panel-heading"><b>Ingresando Resultados Muestra</b>: @Html.DisplayText("lblMuestraCodigo")</div>
        <div class="panel-body form-inline">
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Tipo Muestra")
                </div>
                <div class="col-md-10">
                    @Html.DisplayText("TipoMuestraNombre")
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Prestación")
                </div>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.PrestacionId, (SelectList)ViewBag.ddlPrestaciones, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Método")
                </div>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.MetodoId, (SelectList)ViewBag.ddlMetodos, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Norma")
                </div>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.NormaId, (SelectList)ViewBag.ddlNormas, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Límite Cuantificación")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.LimiteCuantificacionId, (SelectList)ViewBag.ddlLimitesCuantificaciones, new { @class = "chosen-select input-sm" })
                </div>
                <div class="col-md-2">
                    @Html.Label("Límite Detección")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.LimiteDeteccionId, (SelectList)ViewBag.ddlLimitesDetecciones, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("LMP")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.LimiteMaximoPermitidoId, (SelectList)ViewBag.ddlLimitesMaximosPermitidos, new { @class = "chosen-select input-sm" })
                </div>
                <div class="col-md-2">
                    @Html.Label("Unidad de Medida")
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.UnidadMedidaId, (SelectList)ViewBag.ddlUnidadesMedida, new { @class = "chosen-select input-sm" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Analitos")
                </div>
                <div id="chkAnalitos" class="col-md-10">
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Resultado")
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Resultado, string.Empty, new { maxlength = 250, @class = "form-control", required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("Observación")
                </div>
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Observacion, new { maxlength = 250, @class = "form-control", @title = "Observación", required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-offset-2 col-md-2">
                    <button type="button" class="btn btn-sm btn-default btn-block" id="btnAgregarAnalito"><span class="glyphicon glyphicon-plus"></span> Agregar Analito</button>
                </div>
            </div>
        </div>
    </div>
    <input type="submit" value="jojo" />

    <div id="gridContainer">
        @Html.Partial("_GridIngresoResultados", Model.ResultadosAnalitos)
    </div>
    <div class="row">
        <div class="col-md-offset-2 col-md-2">
            <button type="submit" class="btn btn-primary btn-block" id="btnConfirmarResultado"><span class="glyphicon glyphicon-floppy-disk"></span> Guardar Resultados</button>
        </div>
    </div>

}
<div id="modalRechazoContainer">
    @Html.Partial("_ConfirmarRechazoModal")
</div>
<script type="text/javascript">
    $(document).ready(function () {

        gridFunctionCheckAll();


        $('#PrestacionId, #MetodoId').change(function (e) {

            $.ajax({
                url: "@Url.Action("ObtenerPorMetodoPrestacion", "Analitos")",
                method: "GET",
                data: {
                    prestacionId: $("#PrestacionId").val(),
                    metodoId: $("#MetodoId").val()
                },
                success: function (result) {

                    var contenido = '';
                    $.each(result, function (index, value) {
                        contenido += '<div class="col-md-3"><label>';
                        contenido += '<input type="checkbox" value=' + value.Id + ' id="checkboxId">';
                        contenido += ' ' + value.Nombre + '</label></div>';
                    });
                    $("#chkAnalitos").html(contenido);
                }
            });
        });
        $('#btnAgregarAnalito').click(function (e) {
            var analitosIds = [];

            $('input#checkboxId:checked').each(function () {
                analitosIds.push($(this).val());
            });

            $.ajax({
                url: "@Url.Action("AgregarResultadoAnalito", "Analitos")",
                method: "POST",

                data: {
                    muestraIdList: JSON.parse('@Html.Raw(Json.Encode(ViewBag.MuestraIdList))'),
                    examenIdList: JSON.parse('@Html.Raw(Json.Encode(ViewBag.ExamenIdList))'),
                    analitoIdList: analitosIds,
                    prestacionId: $("#PrestacionId").val(),
                    metodoId: $("#MetodoId").val(),
                    normaId: $("#NormaId").val(),
                    limiteCuantificacionId: $("#LimiteCuantificacionId").val(),
                    limiteDeteccionId: $("#LimiteDeteccionId").val(),
                    limiteMaximoPermitidoId: $("#LimiteMaximoPermitidoId").val(),
                    unidadMedidaId: $("#UnidadMedidaId").val(),
                    resultado: $("#Resultado").val(),
                    observacion: $("#Observacion").val(),
                    resultadosAnalitos: $("#resultadosAnalitos").val()
                },

                success: function (result) {
                    $("#gridContainer").html(result);
                    renderAlert();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.responseText + " Ha ocurrido un error.");
                }
            });
        });

        $('#PrestacionId').trigger("change");
    });


</script>

Laboratorios/Views/Resultados/ParaIngresoResultados.cshtml
@using Isp.Laboratorios.Models
@model IEnumerable<Isp.Laboratorios.Models.ViewModels.MuestraViewModel>
@{
    @section Scripts {
        @Scripts.Render("~/bundles/js-chosen")
        @Styles.Render("~/bundles/css-chosen")
        @Scripts.Render("~/bundles/js-grid")
        @Scripts.Render("~/bundles/js-blockUI")
    }
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Ingreso de Resultados";
}
@using (Html.BeginForm("ParaIngresoResultados", "Resultados", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    Html.RenderPartial("_Busqueda", (FiltroBusqueda)ViewBag.FiltroBusqueda);

}
<div id="gridContainer">
    @Html.Partial("_GridParaIngresoResultados", Model)
</div>
<div id="modalRechazoContainer">
    @Html.Partial("_ConfirmarRechazoModal")
</div>

<script type="text/javascript">
    $(document).ready(function () {

        gridFunctionCheckAll();
        var muestrasId = [];

        $("#btnRechazar, #btnRechazarBottom").click(function () {

            muestrasId = [];

            $('#gridCheckAll input#checkboxId:checked').each(function () {
                muestrasId.push($(this).val());
            });
            if (muestrasId.length > 0) {

                obtenerMotivosRechazo(muestrasId);

                $(".modal-body #muestrasIdChecked").val(muestrasId);
                $('.modal-content #formConfirmarRechazo').attr('action', "@Url.Action("RechazarARecepcionLaboratorio", "Resultados")");

                $('#modalConfirmarRechazo').modal('show');
            }
            else {
                alert("seleccione muestras para rechazar");
            }
        });
        $("#btnIngresoResultados, #btnIngresoResultadosBottom").click(function () {

            var examenesId = [];
            $('#gridCheckAll input#checkboxId:checked').each(function () {

                $($(this).parents('tr').find('a')).each(function () {
                    examenesId.push($(this).data('examenid'));
                });

            });
            if (examenesId.length > 0) {

                $.ajax({
                    url: "@Url.Action("IngresoResultados", "Resultados")",
                    type: 'POST',
                    data: { examenesId: examenesId },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.responseText + " Ha ocurrido un error.");
                    },
                    success: function (data) {
                        $("#mainContainer").html(data);
                        $('.chosen-select').chosen();
                    }
                });

            }
            else {
                alert("seleccione muestras para ingreso de resultados");
            }
        });

        $('#gridCheckAll a').click(function () {
            $("#modalContainer").html("")
                                .load($(this)
                                .data("urlaction")).modal('show');

        });
    });


</script>